name: fastlink-platform

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes: 
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - fastlink-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - fastlink-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastlink-net

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - fastlink-net

  identity-service:
    build:
      context: ./services/identity-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_PORT: 8080
      ENTITY_SERVICE_BASE_URL: http://entity-service:8081
      DB_URL: jdbc:postgresql://ep-summer-field-amn2wvfd-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_9eR8pasqoIyJ
      JWT_SECRET_BASE64: QjBqbW16RTV5Kzl2ejRmbWl6WDJ3Vnh3QlM0YmI4M2Q2a2pQd2dQWGNiOD0=
      JWT_ISSUER: fast-link-identity
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - fastlink-net

  entity-service:
    build:
      context: ./services/entity-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      identity-service:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      DB_URL: jdbc:postgresql://ep-red-mud-aneu35a9-pooler.c-6.us-east-1.aws.neon.tech/entity_db?sslmode=require&channelBinding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_yr9zeWTNLM4o 
      IDENTITY_BASE_URL: http://identity-service:8080
      IDENTITY_USER_EXISTS_PATH: /api/v1/internal/users/{userId}/exists
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ENTITY_TOPIC_CREATED: fastlink.entity.created.v1
      ENTITY_TOPIC_UPDATED: fastlink.entity.updated.v1
      ENTITY_TOPIC_DELETED: fastlink.entity.deleted.v1
      ENTITY_TOPIC_MEMBER_ASSIGNED: fastlink.entity.member.assigned.v1
    ports:
      - "8081:8081"
    networks:
      - fastlink-net

  publication-service:
    build:
      context: ./services/publication-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      entity-service:
        condition: service_started
      kafka:
        condition: service_started
      minio:
        condition: service_started
    environment:
      SERVER_PORT: 8082
      DB_URL: jdbc:postgresql://ep-blue-cell-amxmsbaz-pooler.c-5.us-east-1.aws.neon.tech/publication_db?sslmode=require&channelBinding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_fFWkqSbs53BU
      ENTITY_BASE_URL: http://entity-service:8081
      ENTITY_PERMISSION_CHECK_PATH: /api/v1/internal/entities/{entiteId}/permissions/check
      NOTIFICATION_BASE_URL: http://notification-service:8087
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PUBLICATION_TOPIC_CREATED: fastlink.publication.created.v1
      JWT_SECRET_BASE64: QjBqbW16RTV5Kzl2ejRmbWl6WDJ3Vnh3QlM0YmI4M2Q2a2pQd2dQWGNiOD0=
      JWT_ISSUER: fast-link-identity
    ports:
      - "8082:8082"
    networks:
      - fastlink-net

  event-service:
    build:
      context: ./services/event-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      entity-service:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: 8083
      DB_URL: jdbc:postgresql://ep-holy-dream-aniux2tl-pooler.c-6.us-east-1.aws.neon.tech/event_db?sslmode=require&channelBinding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_BkzYagFq15MG
      ENTITY_BASE_URL: http://entity-service:8081
      ENTITY_PERMISSION_CHECK_PATH: /api/v1/internal/entities/{entiteId}/permissions/check
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENT_TOPIC_CREATED: fastlink.event.created.v1
    ports:
      - "8083:8083"
    networks:
      - fastlink-net

  community-service:
    build:
      context: ./services/community-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_PORT: 8084
      DB_URL: jdbc:postgresql://ep-jolly-mouse-amjbwuxz-pooler.c-5.us-east-1.aws.neon.tech/community_db?sslmode=require&channelBinding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_4m9cXlpZqEeU
      ENTITY_BASE_URL: http://entity-service:8081
      ENTITY_PERMISSION_CHECK_PATH: /api/v1/internal/entities/{entiteId}/permissions/check
      NOTIFICATION_BASE_URL: http://notification-service:8087
      JWT_SECRET_BASE64: QjBqbW16RTV5Kzl2ejRmbWl6WDJ3Vnh3QlM0YmI4M2Q2a2pQd2dQWGNiOD0=
      JWT_ISSUER: fast-link-identity
      WEBSOCKET_ALLOWED_ORIGINS: "*"
    ports:
      - "8084:8084"
    networks:
      - fastlink-net

  request-service:
    build:
      context: ./services/request-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      entity-service:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: 8085
      DB_URL: jdbc:postgresql://ep-square-king-a49eb7u4-pooler.us-east-1.aws.neon.tech/request_db?sslmode=require&channelBinding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_UK35regnVYbN
      ENTITY_BASE_URL: http://entity-service:8081
      ENTITY_PERMISSION_CHECK_PATH: /api/v1/internal/entities/{entiteId}/permissions/check
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REQUEST_TOPIC_SUBMITTED: fastlink.request.submitted.v1
      REQUEST_TOPIC_APPROVED: fastlink.request.approved.v1
      REQUEST_TOPIC_REJECTED: fastlink.request.rejected.v1
    ports:
      - "8085:8085"
    networks:
      - fastlink-net

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: 8087
      DB_URL: jdbc:postgresql://ep-morning-water-amndb0ln-pooler.c-5.us-east-1.aws.neon.tech/notification_db?sslmode=require&channel_binding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_oy7YCHfW1TLE
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: notification-service
      EVENT_TOPIC_CREATED: fastlink.event.created.v1
      REQUEST_TOPIC_SUBMITTED: fastlink.request.submitted.v1
      REQUEST_TOPIC_APPROVED: fastlink.request.approved.v1
      REQUEST_TOPIC_REJECTED: fastlink.request.rejected.v1
      WEBSOCKET_ALLOWED_ORIGINS: "*"
    ports:
      - "8087:8087"
    networks:
      - fastlink-net

  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: 8088
      DB_URL: jdbc:postgresql://ep-misty-credit-andnetfk-pooler.c-6.us-east-1.aws.neon.tech/analytics_db?sslmode=require&channel_binding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_Hp7oP9zrslfa
      ENTITY_BASE_URL: http://entity-service:8081
      ENTITY_PERMISSION_CHECK_PATH: /api/v1/internal/entities/{entiteId}/permissions/check
      NOTIFICATION_BASE_URL: http://notification-service:8087
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: analytics-service
      PUBLICATION_TOPIC_CREATED: fastlink.publication.created.v1
      EVENT_TOPIC_CREATED: fastlink.event.created.v1
      REQUEST_TOPIC_SUBMITTED: fastlink.request.submitted.v1
      REQUEST_TOPIC_APPROVED: fastlink.request.approved.v1
      REQUEST_TOPIC_REJECTED: fastlink.request.rejected.v1
      ENTITY_TOPIC_MEMBER_ASSIGNED: fastlink.entity.member.assigned.v1
    ports:
      - "8088:8088"
    networks:
      - fastlink-net

  admin-service:
    build:
      context: ./services/admin-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVER_PORT: 8089
      DB_URL: jdbc:postgresql://ep-floral-lab-anyb9djd-pooler.c-6.us-east-1.aws.neon.tech/admin_db?sslmode=require&channel_binding=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_ZdTX3V8Bkntf
      JWT_SECRET_BASE64: QjBqbW16RTV5Kzl2ejRmbWl6WDJ3Vnh3QlM0YmI4M2Q2a2pQd2dQWGNiOD0=
      JWT_ISSUER: fast-link-identity
    ports:
      - "8089:8089"
    networks:
      - fastlink-net

  api-gateway:
    build:
      context: ./gateway/api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      identity-service:
        condition: service_healthy
      entity-service:
        condition: service_started
      publication-service:
        condition: service_started
      event-service:
        condition: service_started
      community-service:
        condition: service_started
      request-service:
        condition: service_started
      notification-service:
        condition: service_started
      analytics-service:
        condition: service_started
      admin-service:
        condition: service_started
    environment:
      GATEWAY_PORT: 8086
      IDENTITY_SERVICE_URI: http://identity-service:8080
      ENTITY_SERVICE_URI: http://entity-service:8081
      PUBLICATION_SERVICE_URI: http://publication-service:8082
      EVENT_SERVICE_URI: http://event-service:8083
      COMMUNITY_SERVICE_URI: http://community-service:8084
      REQUEST_SERVICE_URI: http://request-service:8085
      NOTIFICATION_SERVICE_URI: http://notification-service:8087
      ANALYTICS_SERVICE_URI: http://analytics-service:8088
      ADMIN_SERVICE_URI: http://admin-service:8089
      COMMUNITY_WS_URI: ws://community-service:8084
      NOTIFICATION_WS_URI: ws://notification-service:8087
      JWT_SECRET_BASE64: QjBqbW16RTV5Kzl2ejRmbWl6WDJ3Vnh3QlM0YmI4M2Q2a2pQd2dQWGNiOD0=
      JWT_ISSUER: fast-link-identity
      RATE_LIMIT_ENABLED: "false"
      RATE_LIMIT_REQUESTS_PER_WINDOW: 120
      RATE_LIMIT_WINDOW_SECONDS: 60
    ports:
      - "8086:8086"
    networks:
      - fastlink-net

networks:
  fastlink-net:
    driver: bridge

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  redis_data:
  minio_data:
