server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: event-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-blue-cell-amxmsbaz-pooler.c-5.us-east-1.aws.neon.tech/event_db?sslmode=require&channelBinding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false

  flyway:
    # On réutilise les mêmes variables d'environnement que le datasource
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # Emplacement par défaut, mais c'est bien de le préciser
    locations: classpath:db/migration
    # Optionnel : Si votre BDD n'est pas vide et que vous voulez que Flyway ignore l'existant
    # baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          add:
            type:
              headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

integration:
  entity:
    base-url: ${ENTITY_BASE_URL:http://localhost:8081}
    permission-check-path: ${ENTITY_PERMISSION_CHECK_PATH:/api/v1/internal/entities/{entiteId}/permissions/check}
    connect-timeout-ms: ${ENTITY_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${ENTITY_READ_TIMEOUT_MS:5000}
  notification:
    base-url: ${NOTIFICATION_BASE_URL:http://localhost:8087}
    connect-timeout-ms: ${NOTIFICATION_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${NOTIFICATION_READ_TIMEOUT_MS:5000}

messaging:
  topics:
    event-created: ${EVENT_TOPIC_CREATED:fastlink.event.created.v1}

security:
  jwt:
    secret: ${JWT_SECRET_BASE64}
    issuer: ${JWT_ISSUER:fast-link-identity}

logging:
  level:
    org.springframework.web: INFO
